FROM  ubuntu@sha256:7cfe75438fc77c9d7235ae502bf229b15ca86647ac01c844b272b56326d56184
WORKDIR /constellation
ADD https://github.com/edgelesssys/constellation/archive/refs/tags/v2.1.0.tar.gz /constellation/constellation.tar.gz
RUN tar xfz constellation.tar.gz
