FROM reprod:build as build

WORKDIR /constellation/
COPY go_cgo/go.mod .
COPY go_cgo/main.go .
RUN CGO_ENABLED=1 go build -o main -buildvcs=false -trimpath -ldflags "-s -w -buildid=''"

FROM gcr.io/distroless/static:nonroot
COPY --from=build /constellation/main /main
ENTRYPOINT ["/main"]
