#defaultBaseImage: leongross/alpine-libcryptsetup:base
baseImageOverrides:
  github.com/edgelesssys/constellation/v2/disk-mapper/cmd: leongross/alpine-libcryptsetup:base

builds:
- id: cli
  dir: .
  main: ./cli/
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -extldflags "-static"

- id: disk-mapper
  dir: .
  main: ./disk-mapper/cmd
  env:
  - CGO_ENABLED=1
  ldflags:
  - -s -w
